<!--<!DOCTYPE html>-->
<!--<html>-->
<!--    <head>-->
<!--        <meta charset="utf-8"/>-->
<!--        <title>Slim 3</title>-->
<!--        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>-->
<!--        <style>-->
<!--            body {-->
<!--                margin: 50px 0 0 0;-->
<!--                padding: 0;-->
<!--                width: 100%;-->
<!--                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;-->
<!--                text-align: center;-->
<!--                color: #aaa;-->
<!--                font-size: 18px;-->
<!--            }-->
<!---->
<!--            h1 {-->
<!--                color: #719e40;-->
<!--                letter-spacing: -3px;-->
<!--                font-family: 'Lato', sans-serif;-->
<!--                font-size: 100px;-->
<!--                font-weight: 200;-->
<!--                margin-bottom: 0;-->
<!--            }-->
<!--        </style>-->
<!--    </head>-->
<!--    <body>-->
<!--        <h1>Slim</h1>-->
<!--        <div>a microframework for PHP</div>-->
<!---->
<!--        --><?php //if (isset($name)) : ?>
<!--            <h2>Hello --><?//= htmlspecialchars($name); ?><!--!</h2>-->
<!--        --><?php //else: ?>
<!--            <p>Try <a href="http://www.slimframework.com">SlimFramework</a>-->
<!--        --><?php //endif; ?>
<!--    </body>-->
<!--</html>-->

<?php
/**
 * Created by PhpStorm.
 * User: ivan
 * Date: 27/1/2017
 * Time: 8:31 PM
 */

?>

<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--jquery-->
    <script src="js/jquery-3.1.1.min.js"></script>
    <!--styles-->
    <!--bootstrap-->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <!--custom-->
    <link rel="stylesheet" href="css/custom.css">
    <script src="js/custom.js"></script>


    <title>IVWMS</title>
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">IVWMS</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#" id="btnPagos">Pagos</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Page Content -->
<div class="container">

    <div id="mainContainer">

    </div>

    <!--
    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>Bienvenido</h1>
        </div>
    </div>
    -->
    <!-- /.row -->

</div>
<!-- /.container -->

<!-- jQuery Version 1.11.1 -->
<script src="js/jquery-3.1.1.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

</body>
</html>
